# Generated by Django 5.0.4 on 2024-04-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('DOSAGE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DOSAGE_LIST', models.CharField(max_length=15)),
            ],
        ),
    ]
