# Generated by Django 5.0.4 on 2024-04-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOSAGE_LIST', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='DOSAGE_LIST',
        ),
    ]
