# Generated by Django 5.0.4 on 2024-04-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('ORDER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CUSTOMER_NAME', models.CharField(max_length=150)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONE_NUMBER', models.CharField(max_length=10)),
                ('PRODUCT', models.CharField(max_length=50)),
                ('DOSAGE', models.IntegerField()),
                ('ADDRESS', models.TextField()),
                ('PINCODE', models.CharField(max_length=10)),
                ('COUNTRY', models.CharField(max_length=50)),
                ('ORDER_STATUS', models.CharField(default='Pending', max_length=50)),
                ('ORDER_DATE', models.DateField(auto_now_add=True)),
                ('ESTIMATED_DATE_OF_DELIVERY', models.DateField()),
                ('DELIVERY_METHOD', models.CharField(max_length=50)),
                ('INVOICE_NUMBER', models.CharField(max_length=50)),
                ('REMARKS', models.TextField(null=True)),
            ],
        ),
    ]
