# Generated by Django 5.0.4 on 2024-04-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='DELIVERY_METHOD',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='ESTIMATED_DATE_OF_DELIVERY',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='INVOICE_NUMBER',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='ORDER_STATUS',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
