# Generated by Django 5.0.4 on 2024-04-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_orderdetails_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='ESTIMATED_DATE_OF_DELIVERY',
            field=models.DateField(blank=True, null=True),
        ),
    ]
