# Generated by Django 5.0.4 on 2024-04-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_orderdetails_estimated_date_of_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='DELIVERY_METHOD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='INVOICE_NUMBER',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='REMARKS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
