# Generated by Django 5.0.4 on 2024-04-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_orderdetails_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='PO_NUMBER',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
