# Generated by Django 5.0.4 on 2024-04-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logisticsusers',
            fields=[
                ('USER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('USER_NAME', models.CharField(max_length=150)),
                ('PASSWORD', models.CharField(max_length=128)),
            ],
        ),
    ]
